"""empty message

Revision ID: 317454b030e1
Revises: 4c15b56417ac
Create Date: 2020-01-05 12:01:22.732691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317454b030e1'
down_revision = '4c15b56417ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'users', ['bauid'], ['uid'])
    op.create_foreign_key(None, 'commits', 'users', ['cau'], ['uid'])
    op.create_foreign_key(None, 'commits', 'blogs', ['bid'], ['bid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###
