"""empty message

Revision ID: b38e37b74b7e
Revises: 317454b030e1
Create Date: 2020-01-05 18:51:35.736226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38e37b74b7e'
down_revision = '317454b030e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'users', ['bauid'], ['uid'])
    op.create_foreign_key(None, 'commits', 'blogs', ['bid'], ['bid'])
    op.create_foreign_key(None, 'commits', 'users', ['cau'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###
